---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerberus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tool: Cerberus
  template:
    metadata:
      labels:
        tool: Cerberus
    spec:
      serviceAccountName: useroot
      containers:
        - name: cerberus
          securityContext:
            privileged: true
          image: quay.io/openshift-scale/cerberus
          command: ["/bin/sh", "-c"]
          args: ["python3 start_cerberus.py -c config/config.yaml"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/root/.kube"
              name: config
            - mountPath: "/root/cerberus/config"
              name: cerberus-config
      volumes:
        - name: config
          configMap:
            name: kube-config
        - name: cerberus-config
          configMap:
            name: cerberus-config
---
apiVersion: v1
kind: Service
metadata:
  name: cerberus-service
spec:
  type: NodePort
  selector:
    tool: Cerberus
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
